/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airlinereservationsystem;

import com.mysql.cj.jdbc.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jing
 */
public class UpdateAirlinePrice extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAirlinePrice
     */
    public UpdateAirlinePrice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPriceTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTo = new javax.swing.JTextField();
        jAddRoute = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPrice = new javax.swing.JTextField();
        jUpdateRoute = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPriceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jPriceTable);

        jButton1.setText("Current Routes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("From");

        jFrom.setText("IATA CODE");

        jLabel3.setText("To");

        jTo.setText("IATA CODE");

        jAddRoute.setText("Add New Route");
        jAddRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddRouteActionPerformed(evt);
            }
        });

        jLabel4.setText("Price");

        jUpdateRoute.setText("Update Route");
        jUpdateRoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateRouteActionPerformed(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jAddRoute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUpdateRoute)
                .addGap(378, 378, 378))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddRoute)
                    .addComponent(jUpdateRoute))
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        List all the routes with price in the price table
        */
        listAllRoutes();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jAddRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddRouteActionPerformed
        // Insert new route to price table
        Getconnection con = new Getconnection();
         
         try{
             String from = jFrom.getText();
             String to = jTo.getText();
             int price = Integer.parseInt(jPrice.getText());
             
             Connection conn = con.getConnection();
             String insertQuery = "Insert into price values(?, ?, ?)";
             PreparedStatement pstmt = conn.prepareStatement(insertQuery);
           
             pstmt.setString(1, from);
             pstmt.setString(2, to);
             pstmt.setInt(3, price);
             
             int rs = pstmt.executeUpdate();
             if(rs == 1){
                listAllRoutes();
            }
            else{
                JOptionPane.showMessageDialog(null, "Failed insertion",
                        "Alert", JOptionPane.INFORMATION_MESSAGE);
            }
             
         }
         catch(Exception e){
             System.out.println("Failed in insertion of data");
             e.printStackTrace();
         }
        
        JOptionPane.showMessageDialog(null, "Route successfully added.", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jAddRouteActionPerformed

    private void jUpdateRouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateRouteActionPerformed
        // TODO add your handling code here:
        updateRoute();
    }//GEN-LAST:event_jUpdateRouteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Return to admin panel
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listAllRoutes(){
        Getconnection con = new Getconnection();
         
         Vector<String> col = new Vector<String>();
         Vector<Vector> dat = new Vector<Vector>();
         try{
             Connection conn = con.getConnection();
             col.add("Departure");
             col.add("Arrival");
             col.add("Price");
             
             String selectQuery = "Select * from price";
             ResultSet rs = conn.createStatement().executeQuery(selectQuery);
             dat.clear();
             while(rs.next()){
                 Vector<String> v = new Vector<String>();
                 v.add(rs.getString("location1"));
                 v.add(rs.getString("location2"));
                 v.add(Integer.toString(rs.getInt("price")));
             
                 dat.add(v);
             }
             
         }
         catch(Exception e){
             System.out.println("Failed populating data");
             e.printStackTrace();
         }
         jPriceTable.setModel(new DefaultTableModel(dat, col){
             @Override
             public boolean isCellEditable(int row, int column) {
                return false;
             }
         });
    }
    
    private void updateRoute(){
        Getconnection con = new Getconnection();
         
         try{
             String from = jFrom.getText();
             String to = jTo.getText();
             int price = Integer.parseInt(jPrice.getText());
             
             Connection conn = con.getConnection();
             String insertQuery = "update price set price=? where location1=? and location2=?";
             PreparedStatement pstmt = conn.prepareStatement(insertQuery);
           
             pstmt.setInt(1, price);
             pstmt.setString(2, from);
             pstmt.setString(3, to);

             
             int rs = pstmt.executeUpdate();
             if(rs == 1){
                listAllRoutes();
            }
            else{
                JOptionPane.showMessageDialog(null, "Failed updating",
                        "Alert", JOptionPane.INFORMATION_MESSAGE);
            }
             
         }
         catch(Exception e){
             System.out.println("Failed in insertion of data");
             e.printStackTrace();
         }
        
        JOptionPane.showMessageDialog(null, "Route successfully added.", "Message", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAirlinePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAirlinePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAirlinePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAirlinePrice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAirlinePrice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddRoute;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jFrom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jPrice;
    private javax.swing.JTable jPriceTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTo;
    private javax.swing.JButton jUpdateRoute;
    // End of variables declaration//GEN-END:variables
}
